apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  namespace: default
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: hanatareka/udagram-reverseproxy:latest
        imagePullPolicy: Always          
        ports:
        - containerPort: 8080
      restartPolicy: Always
